<?php
return [
    'bootstrap' => '/bower_components/bootstrap/dist/css/bootstrap.min.css',
    'index' => '/bower_components/css/index',
    'home-css' => '/css/home.css',
    'jquery' => '/bower_components/jquery/dist/jquery.min.js',
    'bootstrap-bundle' => '/bower_components/bootstrap/dist/js/bootstrap.bundle.min.js',
    'home-js' => '/js/home.js',
    'all-min-css' => '/bower_components/Font-Awesome/css/all.min.css',
    'app-css' => '/css/app.css',
    'app-js' => '/js/app.js',
    'student-img' => '/student_img/',
    'admin-img' => '/admin_img/',
    'student-default-img' => '/student_img/default_avatar.jpg',
    'registration-instruction-video' => 'https://www.youtube.com/embed/kRJ3IMQU_pE',
    'registration-instruction-document' => 'http://ueb.edu.vn/Uploads/file/diepmtcn@gmail.com/2016/07/21/Huong%20dan%20su%20dung%20cong%20thong%20tin%20.pdf',
    'role_admin' => 2,
    'role_student' => 1,
    'sb-admin' => 'SB Admin',
    'admin-css' => '/css/admin.css',
    'admin-js' => '/js/admin.js',
];
